os: linux
language: python

arch:
    - amd64
    - ppc64le

python:
    - pypy3
    - 3.6
    - 3.7
    - 3.8
    - 3.9

env:
    - TOXENV=test

matrix:
    include:
        - python: 3.6
          env: TOXENV=stylecheck
        #Adding power support architecture
        - python: 3.6
          env: TOXENV=stylecheck
          arch: ppc64le
    exclude:
         - python: pypy3
           arch: ppc64le
            
install:
    - pip install tox

script:
    - tox
